# Generated by Django 5.1.7 on 2025-04-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskcategory_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(related_name='tasks', to='task.taskcategory'),
        ),
    ]
