# Generated by Django 5.1.7 on 2025-04-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_category_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
